language: go
go:
 - 1.4.1
 - release
 - tip

services:
  - redis-server

before_install:
 - export PATH=/home/travis/gopath/bin:$PATH

install:
 - go get github.com/smartystreets/goconvey/convey
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls
 - go install github.com/mattn/goveralls
 - go get .

script:
 - go test -covermode=count -coverprofile=profile.cov .
 - goveralls -coverprofile=profile.cov -service=travis-ci
